// DO NOT EDIT THIS FILE
// Generated by tools/gen-pages.py

#pragma once

#define PAGE_ACTIONS_HTML 0
#define PAGE_ACTIONS_JS 1
#define PAGE_BRUTE_HTML 2
#define PAGE_BRUTE_JS 3
#define PAGE_CONNECT_HTML 4
#define PAGE_MAIN_HTML 5
#define PAGE_MAIN_JS 6
#define PAGE_PARA_JS 7
#define PAGE_PARA_HTML 8
#define PAGE_GLOBAL_PARA_JS 9
