// DO NOT EDIT THIS FILE
// Generated by tools/gen-pages.py

#pragma once

#define RMS_PAGE_ACTIONS_HTML 0
#define RMS_PAGE_ACTIONS_JS 1
#define RMS_PAGE_BRUTE_HTML 2
#define RMS_PAGE_BRUTE_JS 3
#define RMS_PAGE_CONNECT_HTML 4
#define RMS_PAGE_GLOBAL_PARA_JS 5
#define RMS_PAGE_MAIN_HTML 6
#define RMS_PAGE_MAIN_JS 7
#define RMS_PAGE_PARA_HTML 8
#define RMS_PAGE_PARA_JS 9
