// DO NOT EDIT THIS FILE
// Generated by tools/gen-pages.py

#pragma once

extern const char* pages[];
#define RMS_PAGE_REEF_MIN_JS 0
#define RMS_PAGE_SIMPLE_MIN_CSS 1
#define RMS_PAGE_ACTIONS_HTML 2
#define RMS_PAGE_BRUTE_HTML 3
#define RMS_PAGE_CONNECT_HTML 4
#define RMS_PAGE_MAIN_HTML 5
#define RMS_PAGE_PARA_HTML 6
#define RMS_PAGE_ACTIONS_JS 7
#define RMS_PAGE_BRUTE_JS 8
#define RMS_PAGE_GLOBAL_PARA_JS 9
#define RMS_PAGE_MAIN_JS 10
#define RMS_PAGE_PARA_JS 11
