// DO NOT EDIT THIS FILE
// Generated by tools/gen-pages.py

void setup_page_actions_html();
void setup_page_actions_js();
void setup_page_brute_html();
void setup_page_brute_js();
void setup_page_connect_html();
void setup_page_main_html();
void setup_page_main_js();
void setup_page_para_js();
void setup_page_para_html();
void setup_page_global_para_js();
