// DO NOT EDIT THIS FILE
// Generated by tools/gen-pages.py

#include "_pages.h";

void setupPages()
{
    setup_page_actions_html();
    setup_page_actions_js();
    setup_page_brute_html();
    setup_page_brute_js();
    setup_page_connect_html();
    setup_page_main_html();
    setup_page_main_js();
    setup_page_para_js();
    setup_page_para_html();
    setup_page_global_para_js();
}

char* pages[10];
