// DO NOT EDIT THIS FILE
// Generated by tools/gen-pages.py

#include "_dictionary.h";

extern char* pages[];

void setup_page_brute_html()
{
    // This file part is generated from ./pages/brute.html
    pages[PAGE_BRUTE_HTML] = R"=====(
<!doctype html>
   <html><head><meta charset="UTF-8"><style>
    * {box-sizing: border-box;}
    body {background: linear-gradient(#003,#77b5fe,#003);background-attachment:fixed;font-size:150%;text-align:center;width:100%;max-width:1000px;margin:auto;}
    h2{text-align:center;color:white;}
    a:link {color:#ccf;text-decoration: none;}
    a:visited {color:#ccf;text-decoration: none;}
    .ri { text-align: right;}
    .Wh { background-color:#fdd;}
    .A { background-color:#ddf;}
    .W { background-color:#f88;}
    .phi { background-color:#ffd;}
    .V { background-color:#ee8;}
    .VA { background-color:#dfd;}
    .Hz,.Enph { background-color:#eeb;}
    .titre{background-color:#ccc; text-align: center;font-weight: bold;}
    .foot { color:white;}
    #date,#dateLinky { color:white;}
    #DataLinky,#dataSmartG,#dataShellyEm {border:10px inset azure; background-color:white;margin:auto;padding:4px;text-align:left;overflow:hidden;display:inline-block;}
    #tableau,#DataESP32,#tableauLinky,#tableauEnphase { background-color:white;display:inline-block;margin:auto;padding:4px;}
    table {border:10px inset azure;}
    td { text-align: left;padding:4px;}
    #LED{position:absolute;top:4px;left:4px;width:0px;height:0px;border:5px solid red;border-radius:5px;}
    .onglets{margin-top:4px;left:0px;font-size:130%;}
    .Baccueil,.Bbrut,.Bparametres,.Bactions{margin-left:20px;border:outset 4px grey;background-color:#333;border-radius:6px;padding-left:20px;padding-right:20px;display:inline-block;}
    .Bbrut{border:inset 8px azure;}
    .pied{display:flex;justify-content:space-between;font-size:14px;color:white;}
    .dispT{display:none;}
    .ce { text-align: center;position:relative;}
    svg { border:10px inset azure;background: linear-gradient(#333,#666,#333);}
    #infoUxIx2,#infoUxI,#infoLinky,#infoEnphase,#infoSmartG,#infoShellyEm{display:none;}
    #donneeDistante{font-size:50%;color:white;text-align:center;margin-bottom:10px;display:none;}
  </style></head>
  <body  onload='LoadParaRouteur();' >
    <div id='LED'></div>
    <div class='onglets'><div class='Baccueil'><a href='/'>Accueil</a></div><div class='Bbrut'><a href='/Brute'>Donn&eacute;es brutes</a></div><div class='Bparametres'><a href='/Para'>Param&egrave;tres</a></div><div class='Bactions'><a href='/Actions'>Actions</a></div></div>
    <h2 id='nom_R'>Routeur Solaire - RMS</h2>
    <div id='date'>Date</div><br><br>
    <div id='infoUxI'>
      <div class='foot' >Tension et Courant sur 20ms</div>
      <div  class='ce'><h3 style='position:absolute;top:20px;right:40px;'><span style='color:red;'>_<span id='Ueff'></span><small> V</small></span>
      <span style='color:lightgreen;'> _<span id='Ieff'></span><small> A</small></span><br>
      <span style='color:white;'> <small>Facteur de puissance : <span id='cosphi'></span></small></span></h3><p id='SVG'></p></div>
    </div>
    <div id='infoUxIx2'>
      <br><br><div class='foot' >Donn&eacute;es brutes capteur JSY-MK-194T</div>
      <div id='tableau'></div>
    </div>
    <div id='infoEnphase'>
      <br><br><div class='foot' >Donn&eacute;es Enphase Envoye-S Metered</div>
      <div id='tableauEnphase'></div>
    </div>
    <div id='infoSmartG'>
      <div class='foot' >Donn&eacute;es SmartGateways</div>
      <div id='dataSmartG'></div>
    </div>
    <div id='infoShellyEm'>
      <div class='foot' >Donn&eacute;es Shelly Em </div>
      <div id='dataShellyEm'></div>
    </div>
    <div id='infoLinky'>
      <div id='dateLinky'></div>
      <div id='tableauLinky'></div>
      <br><br><div class='foot' >Donn&eacute;es brutes Linky en mode standard</div>
      <div><div id='DataLinky' ></div></div>
    </div>
    <div id="donneeDistante">Données distantes</div>
    <div class='foot' >Donn&eacute;es ESP32</div>
    <div><div id='DataESP32' ></div></div><br>
    <div class='pied'><div>Routeur Version : <span id='version'></span></div><div><a href='https:F1ATB.fr' >F1ATB.fr</a></div></div>
    <script src='BruteJS'></script>
    <script src="/ParaRouteurJS"></script>
    <br>
  </body>
</html>

)=====";

} // end of setup_page_brute_html()
